### ISSUE TITLE
getting connect not an attribute

### ISSUE THREAD

**Issue by goochi1** [cosmin/stashy#125]
running:
#!/usr/bin/python
import sys
import os
import stashy

stash = stashy.connect("https://stash.***.co.uk/projects/*REPO*", "", "")
for repo in stash.projects[sys.argv[1]].repos.list():
    for url in repo["links"]["clone"]:
        if (url["name"] == "ssh"):
            os.system("git clone %s" % url["href"])
            break
Getting
Traceback (most recent call last):
  File "./stashy.py", line 4, in <module>
    import stashy
  File "/stashy.py", line 6, in <module>
    stash = stashy.connect("https://stash.***.co.uk/", "", "")
AttributeError: 'module' object has no attribute 'connect'

Please help

**Comment by goochi1** [comment]
Resolved 

But is it possible to clone branches on https?
