### ISSUE TITLE
Documentation on creating a pull request

### ISSUE THREAD

**Issue by lynna-heng** [cosmin/stashy#148]
Hi,

I am trying to use this package to create a pull request from the script. Is there a document that I read or shed some light on this?

Thanks,
Lynna

**Comment by lynna-heng** [comment]
I looked at the module pullrequests.py and found the class below expects to pass in "parent". 
What is the value of "parent'?

class PullRequest(ResourceBase):
    def __init__(self, id, url, client, parent):
    .
    .
    .


Thanks,
Lynna

**Comment by lynna-heng** [comment]
Here's the errors I encountered when I compile the code. The issue is the "parent" parameter, and I don't know what should the right value.   Please shed some light on this.

$python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    creq=req.create("Talking CLI PR Title", "refs/heads/test-pr-python", "refs/heads/master", description='CLI Python', state='OPEN', reviewers="monica")
  File "<string>", line 2, in create
  File "/usr/lib/python2.7/site-packages/stashy/errors.py", line 62, in response_or_error
    response = fn(*args, **kw)
  File "/usr/lib/python2.7/site-packages/stashy/pullrequests.py", line 264, in create
    fromRef=self._make_ref(fromRef, "fromRef"),
  File "/usr/lib/python2.7/site-packages/stashy/pullrequests.py", line 248, in _make_ref
    repo = self._parent.get()
AttributeError: 'str' object has no attribute 'get'

=================================================
$ cat test.py
import stashy
from stashy.pullrequests import PullRequest, PullRequests
stash=stashy.connect("http://mybitbucker.com:7990", "admin", "admin")
client=stash._client;
parent=""  
req=PullRequests("http://mybitbucker.com:7990", client, parent)
creq=req.create("Talking CLI PR Title", "refs/heads/test-pr-python", "refs/heads/master", description='CLI Python', state='OPEN', reviewers="monica")

**Comment by rwilcox** [comment]
Ok, so here's what worked for me

```python
import stashy
from stashy.pullrequests import PullRequest, PullRequests
stash=stashy.connect("http://mybitbucker.com:7990", "admin", "admin")
client=stash._client;

projectKey = 'PROJECT_KEY_FROM_THAT_PROJECT_LIST_COLUMN_IN_THE_UI'
repoKey = 'MY_DESTINATION_REPO'

project = stash.projects[projectKey]
parent= project.repos['repoKey]

req=PullRequests("/projects/" + projectKey + "/repos/" + repoKey + "/pull-requests", client, parent)
creq=req.create("Talking CLI PR Title", "refs/heads/test-pr-python", "refs/heads/master", description='CLI Python', state='OPEN', reviewers="monica")
```
